Lab12
SvetlanaMaximenko/Lessons pull request #16
Opened 2023-04-03 11:33 UTC by SvetlanaMaximenko

Pull Lab12 and Lab11 new version

2023-04-03 11:41 UTC, SvetlanaMaximenko commented
в этом pull-запросе находится также и 11-я лабораторная, посмотрите, пожалуйста

2023-04-03 13:28 UTC, vimoro requested changes

2023-04-03 13:28 UTC, vimoro commented on Lab11/Lab11.py
тут все хорошо

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
> +class decorator():
лишние урглые скобки: если ни от кого не наследуешься, то и скобки не нужны

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
> +        if len(args) ==0  and len(kwargs) == 0:
проверка коллекций на пустоту в питоне пишется так:
`if not args and not kwargs`

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
> +        if args != ():
здесь то же самое

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
> +        if len(kwargs) != 0:
и здесь

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
> +            return print(f'Функция {self.func.__name__} вызвана в {time.strftime("%Y-%m-%d %X")} без параметров', end='\n')
здесь нельзя писать return, иначе потеряется вызов продикорированной функции

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
> +        self.func(*args, **kwargs)
здесь лишний вызов функции, т к она вызывается строчкой ниже и возвращается её значение

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
> +def my_add(*Number, **Numbers1) -> int:
имена аргументов должны быть с маленькой буквы

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_2.py
> +class Input_Error(Exception):
имя класса не по pep8, должноь быть как я попросила в прошлом ПР

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_3.py
> +class Input_Error(Exception):
здесь тоже надо поправить

2023-04-03 13:28 UTC, vimoro commented on Lab12/lesson12_1.py
обращаю внимание, этот пул реквест НЕ НАДО ЗАКРЫВАТЬ, надо закоммитить изменения в эту же ветку и запушить

2023-04-03 19:55 UTC, SvetlanaMaximenko commented
Изменения по лаб.12 сделала. Ожидают вашего ревью

2023-04-03 20:03 UTC, vimoro requested changes

2023-04-03 20:03 UTC, vimoro commented on Lab12/lesson12_3.py
> +class input_Error(Exception):
должно быть `InputError`

2023-04-03 20:03 UTC, vimoro commented on Lab12/lesson12_2.py
> +class input_Error(Exception):
должно быть `InputError`

2023-04-03 20:03 UTC, vimoro commented on Lab12/lesson12_1.py
> +            return print(f'Функция {self.func.__name__} вызвана в {time.strftime("%Y-%m-%d %X")} без параметров', end='\n')
должно быть `print(f'Функция {self.func.__name__} вызвана в {time.strftime("%Y-%m-%d %X")} без параметров', end='\n')`, без return

2023-04-04 05:38 UTC, SvetlanaMaximenko commented
Lab12 version2

2023-04-24 18:12 UTC, merged